package resoft.basLink;

/* Generated by Together */

public interface ModuleBase {
    public static final int SUCCESS = 0;
    public static final int FAIL = -1;

    int execute(Message msg) throws Exception;

    /** @link dependency */
    /*# Message lnkMessage; */
}
