package resoft.basLink;

/* Generated by Together */

public interface Packer {
    /**
     * to Message
     * */
    Message pack(byte[] m) throws PackException;
    /**
     * Message ---->   byte[]
     * */
    byte[] unpack(Message msg);

    /**
     * 从Message中的交易码得到报文格式定义文件
     * */
    public byte[] unpackByFile(Message msg) throws PackException;

    /**
     * 从文件中取得报文格式定义文件
     * @param msg Message
     * @param filePath String   格式定义文件路径，指其在ClassPath中的相对路径
     * */
    public byte[] unpackByFile(Message msg,String filePath) throws PackException;

    /** @link dependency */
    /*# resoft.basLink.Message lnkMessage; */
}
